# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divsion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=75)),
                ('position', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('pres', models.CharField(max_length=75)),
                ('vicepres', models.CharField(max_length=75)),
                ('secretary', models.CharField(max_length=75)),
                ('treasurer', models.CharField(max_length=75)),
                ('webmaster', models.CharField(max_length=75)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
