# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_school_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='editor',
            field=models.CharField(default='N/A', max_length=75),
        ),
        migrations.AlterField(
            model_name='school',
            name='pres',
            field=models.CharField(default='N/A', max_length=75),
        ),
        migrations.AlterField(
            model_name='school',
            name='secretary',
            field=models.CharField(default='N/A', max_length=75),
        ),
        migrations.AlterField(
            model_name='school',
            name='treasurer',
            field=models.CharField(default='N/A', max_length=75),
        ),
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='vicepres',
            field=models.CharField(default='N/A', max_length=75),
        ),
        migrations.AlterField(
            model_name='school',
            name='webmaster',
            field=models.CharField(default='N/A', max_length=75),
        ),
    ]
