# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20170620_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=75),
            preserve_default=False,
        ),
    ]
