# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_division_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='editor_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, verbose_name=b"Editor's Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='pres_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, verbose_name=b"President's Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='secret_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, verbose_name=b"Secretary's Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='treas_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, verbose_name=b"Treasurer's Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='vp_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, verbose_name=b"Vice President's Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='webm_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, verbose_name=b"Webmaster's Email"),
            preserve_default=False,
        ),
    ]
