# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_faq_answer2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
    ]
