# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_remove_faq_answer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='editor_email',
            field=models.CharField(max_length=75, verbose_name="Editor's Email"),
        ),
        migrations.AlterField(
            model_name='school',
            name='newsletter_url',
            field=models.URLField(default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='pres_email',
            field=models.CharField(max_length=75, verbose_name="President's Email"),
        ),
        migrations.AlterField(
            model_name='school',
            name='secret_email',
            field=models.CharField(max_length=75, verbose_name="Secretary's Email"),
        ),
        migrations.AlterField(
            model_name='school',
            name='treas_email',
            field=models.CharField(max_length=75, verbose_name="Treasurer's Email"),
        ),
        migrations.AlterField(
            model_name='school',
            name='vp_email',
            field=models.CharField(max_length=75, verbose_name="Vice President's Email"),
        ),
        migrations.AlterField(
            model_name='school',
            name='webm_email',
            field=models.CharField(max_length=75, verbose_name="Webmaster's Email"),
        ),
    ]
