# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 16:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_auto_20171128_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Divisional Board Member', 'verbose_name_plural': 'Divisional Board Members'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School Club', 'verbose_name_plural': 'School Clubs'},
        ),
        migrations.AlterField(
            model_name='division',
            name='desc',
            field=models.TextField(verbose_name='About the Board Member'),
        ),
        migrations.AlterField(
            model_name='division',
            name='image',
            field=models.ImageField(upload_to='division_photos/', verbose_name="Board Member's Image"),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer3',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(upload_to='school_photos/', verbose_name='School Logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='newsletter_url',
            field=models.URLField(default='#', max_length=300, verbose_name='Newsletter Link'),
        ),
        migrations.AlterField(
            model_name='school',
            name='pres',
            field=models.CharField(default='N/A', max_length=75, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.CharField(default='#', max_length=300, verbose_name='Club Website'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vicepres',
            field=models.CharField(default='N/A', max_length=75, verbose_name='Vice President'),
        ),
    ]
