# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='month',
            field=models.CharField(max_length=30),
        ),
    ]
