# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_body'),
        ('resources', '0002_auto_20170619_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='post',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
