# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170706_0352'),
        ('resources', '0003_newsletter_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
