# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20170706_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='location',
            field=models.CharField(default=b'Division 11', max_length=50),
        ),
    ]
