# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20171128_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutes',
            options={'verbose_name': 'Minute', 'verbose_name_plural': 'Minutes'},
        ),
        migrations.AlterField(
            model_name='minutes',
            name='location',
            field=models.CharField(default='Division 11', max_length=50, verbose_name='Place where Divisional was Held'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='month',
            field=models.DateField(verbose_name='Month of Divisional'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='notes',
            field=models.FileField(upload_to='minutes/', verbose_name='Minutes File'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Linked Post'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='month',
            field=models.CharField(max_length=30, verbose_name='Month of Newsletter'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Linked Post'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Link to Issuu'),
        ),
    ]
