# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Papers0',
        ),
    ]
