# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170619_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='form',
            new_name='name',
        ),
    ]
