# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20170619_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
