# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
