# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_dtc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtc',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dtc_event'),
            preserve_default=False,
        ),
    ]
