# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 01:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_list_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('background_image', models.ImageField(upload_to=b'conventions')),
                ('def_short', ckeditor.fields.RichTextField()),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=75)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to=b'conventions')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Convention')),
            ],
        ),
    ]
