# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_convention_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField()),
                ('description', models.TextField()),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
