# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='school',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
