# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170802_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
