# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170802_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
