# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_convention_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTC',
        ),
    ]
