# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_service_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='list',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='list',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
