# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20170901_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
