# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 16:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20171128_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Fundraiser', 'verbose_name_plural': 'Fundraisers'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Convention Part', 'verbose_name_plural': 'Convention Parts'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service Event', 'verbose_name_plural': 'Service Events'},
        ),
        migrations.AlterField(
            model_name='convention',
            name='def_short',
            field=ckeditor.fields.RichTextField(verbose_name='Short Explanation of Convention'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Name of Convention'),
        ),
        migrations.AlterField(
            model_name='list',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name of Fundraiser'),
        ),
        migrations.AlterField(
            model_name='list',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Post', verbose_name='Related WEBSITE Posts made about Event'),
        ),
        migrations.AlterField(
            model_name='list',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='Link to Event FB Page'),
        ),
        migrations.AlterField(
            model_name='part',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Short Blurb/Description'),
        ),
        migrations.AlterField(
            model_name='part',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Convention', verbose_name='Linked Convention'),
        ),
        migrations.AlterField(
            model_name='part',
            name='header',
            field=models.CharField(max_length=75, verbose_name='Title'),
        ),
    ]
