# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 19:32
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
