# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='/image_main'),
            preserve_default=False,
        ),
    ]
