# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='event_choices',
            field=models.CharField(choices=[(b'DIV', b'Division Events'), (b'FUND', b'Fundraisers'), (b'CLUB', b'Club Events')], default=b'FUND', max_length=4),
        ),
        migrations.AddField(
            model_name='link',
            name='host',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
