# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170706_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date_2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'publish date'),
            preserve_default=False,
        ),
    ]
