# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_pub_date_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date_2']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
