# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_link_show_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name=b'Show in Home Page?'),
        ),
    ]
