# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
