# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='other_post',
            field=models.ManyToManyField(blank=True, related_name='image_posts', to='blog.Post', verbose_name=b'Other Linked Posts'),
        ),
        migrations.AddField(
            model_name='video',
            name='post_related',
            field=models.ManyToManyField(blank=True, related_name='video_posts', to='blog.Post', verbose_name=b'Other Related Posts'),
        ),
    ]
