# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170901_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='other_post',
            field=models.ManyToManyField(blank=True, related_name='image_posts', to='blog.Post', verbose_name='Other Linked Posts'),
        ),
        migrations.AlterField(
            model_name='image',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Show in Home Page?'),
        ),
        migrations.AlterField(
            model_name='link',
            name='event_choices',
            field=models.CharField(choices=[('DIV', 'Division Events'), ('FUND', 'Fundraisers'), ('CLUB', 'Club Events'), ('KWNS', 'Kiwannis Events')], default='FUND', max_length=4, verbose_name='Type of Event'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Primary Post'),
        ),
        migrations.AlterField(
            model_name='link',
            name='other_link',
            field=models.ManyToManyField(blank=True, related_name='links', to='blog.Post', verbose_name='Other Related Posts'),
        ),
        migrations.AlterField(
            model_name='link',
            name='show_screen',
            field=models.BooleanField(default=False, verbose_name='Show on Events List?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body2',
            field=models.TextField(verbose_name='Main Body of Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date_2',
            field=models.DateField(verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_related',
            field=models.ManyToManyField(blank=True, related_name='video_posts', to='blog.Post', verbose_name='Other Related Posts'),
        ),
    ]
