# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 00:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_level', models.CharField(max_length=100, verbose_name=b'Level of Key Club?')),
                ('name', models.CharField(max_length=100, verbose_name=b'Name of Project')),
                ('logo', models.ImageField(upload_to=b'projects/')),
                ('bkgnd_photo', models.ImageField(upload_to=b'projects/')),
                ('def_short', ckeditor.fields.RichTextField()),
                ('video', embed_video.fields.EmbedVideoField()),
                ('extend_desc', ckeditor.fields.RichTextField()),
                ('fundrs_goal', models.IntegerField()),
                ('hours_goal', models.IntegerField()),
            ],
        ),
    ]
