# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='hours_goal',
        ),
        migrations.AlterField(
            model_name='level',
            name='fundrs_goal',
            field=models.IntegerField(verbose_name=b'Fundraising Goal'),
        ),
    ]
