# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170720_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
