# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 22:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_level_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='def_short2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='extend_desc2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
    ]
