# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170901_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='bkgnd_photo',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='level',
            name='fundrs_goal',
            field=models.IntegerField(verbose_name='Fundraising Goal'),
        ),
        migrations.AlterField(
            model_name='level',
            name='key_level',
            field=models.CharField(max_length=100, verbose_name='Level of Key Club?'),
        ),
        migrations.AlterField(
            model_name='level',
            name='logo',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of Project'),
        ),
    ]
