# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 16:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20171128_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Key Club Project', 'verbose_name_plural': 'Key Club Projects'},
        ),
        migrations.AlterField(
            model_name='level',
            name='bkgnd_photo',
            field=models.ImageField(upload_to='projects/', verbose_name='Background Photo'),
        ),
        migrations.AlterField(
            model_name='level',
            name='def_short2',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Short Description of Organization'),
        ),
        migrations.AlterField(
            model_name='level',
            name='extend_desc2',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Extensive Description'),
        ),
        migrations.AlterField(
            model_name='level',
            name='logo',
            field=models.ImageField(upload_to='projects/', verbose_name='Logo of Organization'),
        ),
        migrations.AlterField(
            model_name='level',
            name='video',
            field=embed_video.fields.EmbedVideoField(verbose_name='Video of Organization'),
        ),
    ]
