# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
