# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170416_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
